[package]
name = "nightcycle/switch"
description = "A switch UI: https://material.io/components/switches"
version = "0.1.2"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
isotope = "nightcycle/isotope@1.0.x"
coldfusion = "nightcycle/cold-fusion@1.0.x"
signal = "quenty/signal@^2.0.0-canary"
maid = "quenty/maid@^2.0.1-canary"
